from typing import Dict

ALPHABETS = {
    "RUS": "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ",
    "ENG": "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
}
TEXTS = {
    "ENG": {
        1: """OAUW GK TH HJWVNUMFBW FMEIOWCJ? TH HJWVNUMFBW FMEIOWCJ BM D BWOCFC LAUW ASG UFAWIN LLXHLPYLBIQ, QLHLH GL,  ILRAWLM LR, SGX SPWLYQR LAY UCKNFWQ GY NKC HKIFCKLCQE AG MRKW TWFCHMUEJW YIUK.  S FIVR AFJRPLTHW YVCOQAL MI WFAL XHDAGCWGGG CV RZTN D AGFJXRWK CV RGEX KMO MI  SPGVYVQ LAY LLXHLPYLBIQ ZQ BHVRJNWWGGGM, ZFAVB DPW LNRPWW CQ AGWYG DGKG  LLKBXH RZX WRKHNNHP. S VIPNMMYU RZNM GGXYYUQ JTXLASEFB DJHG D ASEWXJSMIU,  UZBWK ASG XR RZX MDKW MBLLY MBDR S VIPNMMYU BGXM, HVUXJW RZTN WFW BHVRJNWWGGGM  DPW GIW QLHLHB AGMLBW MBH KSVBLLW. MBH AGWYG GFLNUSUMCRLK TLH ASEFHB S  ILREJTG (PMVXLQ SKTAH NJXZHPK MBH UGKX UMMMCQC). OX NKCJXZRPW LJHYC HZ D  AGFJXRWK UV YF BHWCJGUOJQ-LNRPWW-JUMYKUP BWOCFC. EHXHPF XFHALKIQGU WCJGLTF FMEIOWCJL BDTW FUQW SMNUGTNNHQ AG WRKEHH.  WFWR UUC MLODJDR VXGDM CQ QWOYUYD NHLRK, HHOW GGY RD LAYP GK T WRKHNNHP GK "JUMUXMVMJ". MBH MLAYU SFBNV YJX WRLLKIO, QLHLDEW THG GFIOW-MMMJXR VXPLAWL. NKC EHXHPF FUFFAGY LQ EHLH MXMYQ ASEFHB S VIPNMMCQE KRMWCE. MBHQW LSVRWFM  XQW LYPGUHHGSUMIUQ SGX LLUEOGC ETAQCLBW-FMJX UQB ETAQCLBW-WYHX  MWMJTAH. YDFIVR WOYUW VBALRSE WRKHNNHP ZTM ECWG ZRSFW WDNSUFH MX WILLY  FIUC LAUQ GL PUV MJBALLSEFB BWLCJLWW NR BG. THB AGFJXRWK IU ASEWXJSMIU AGGNDGFL XHTAVYV DGK ZLTW FULL XNHFRAHHV:  GFIOW, QLHLDEW, TLLRZFYWGU, VIQRJHF DLV HOWNMM. CQNMM LHDWKM WM LAY SPGVYVQ TR  QKGUA CQDGKGDRAHH LQ HNN LLLH NKC ETWKGFX. IXRHNN LQ LAY SPGVYVQ TR QKGUA  NKC JXMXJLL UUC EHPHB GNN RD LAY PYUACQC. KMIUYYX LHDWKM WM LAY PCUAUQGKF  NKYL VUQ PWMULL AGZRPETNLMF WOUGFZ WDJUNFDRAHH DLV YOULALB LR SL HHCVXX WM  GMBHP HTLWQ GY NKC ETWKGFX. NKC SKCWFEXNLA MGCW GK MBDR HTLW MX MBH KSVBLLW,  PBLAZ VUQ ASKLB MMM IQC GK GRPW HZ WFW UUVGU TLLRZFYWGU HJHPSMCRLK HH WFW  BHIMJFUWGGG BHJV BH VRGKUJC. XBHDJDR, NKC UHHWPGE LHDWKM WM LAIVC HTLWQ GY NKC  ETWKGFX NKYL WCFRSMY WFW YOQALBIQQ LH VH NWKZRPEXX EW SEF WFW HNKCJ IUURK. BH D AGFJXRWK, ZRSJ HZ WFW YCYC XNHFRAHHV YJX, CQ NJBHFGHEY, WFW LUPC SL CQ  Y UTFFSDTNRP. EHMW AGFJXRWKM DPW XFHALKIQGU, LI WFSM NKC HKUFRAVUO BWMULJK HZ  WFWLY ISFVNLMFL UUC KHGHUZTN GGXYYUCFM. IUGYBHDJDR CQNMM NR RZX WRKHNNHP OTM  SPGOCGCV US VSUA NKGFZM DQ HNHFFWW WDPVL IA NMGWKCV IUSCJ MUSCK. LNRPSZY ZYK  ILRTAWYG ZQ T XHTAVY VSUA UV Y JHNDRAGA PYYGYWGU WLXK GK VB KSZHHRAV WRPWL.  UUGLAGHRAV QDQ UTLUGWW IXR TR PDPAHOV CDXWWPGGCF AAKWXGLL, UV Y HTLW MX MBH AGGNUMD  YOQALBIQ. MMMJXR OTM SPGOCGCV US VSUA XHTAVYV YK IOQAZXX FYJWM,  SSFVBHB HTJHP LTJHQ, S MSSCOKCWCJ, HL D NJBHWCJ, PBLAZ VUQ NJBHW Y UHGSJWMY  OGFX II GFYIUKSMCRL SM U WGEX. NKC ETCQ BAYZHPWGWH GK MBDR LAY LLKMLXALBIQQ  LXFOGFZ NKC UHGSSLXL ZFSM NR BG FOVR TX JOYUXX LL KMIUYYX VHDGKY WFW VIPNMMYU  NJHWHCVL QLRZ MBH QGEOWGGG II Y HKIEJWF. NKCKX CQQLKOFRAHHV, UZBWK YJX  GDBW NJ RD GKXLLSKS GCUBGDJ VBALRK TLH NDTWHB AG NKC KTGH QLHLDEW WYYGUX NKYL  AIOBK MBH BSMU.""",
        2: """SRJZT XVFDVKIZT TFETVGKJ KYV GIRTKZTRC MRCLV FW XVFDVKIP CZVJ ZE KYV WRTK KYRK NV TRE RSJKIRTK REU ZCCLJKIRKV GYPJZTRC FSAVTKJ SP UIRNZEXJ REU DFUVCJ. WFI VORDGCV, R UIRNZEX FW R TZITCV ZJ EFK R TZITCV, ZK JLXXVJKJ KYV ZUVR FW R TZITCV. ZE FLI JKLUP FW XVFD NV JVGRIRKV RCC XVFDVKIZT WZXLIVJ ZEKF KNF XIFLGJ: GCREV WZXLIVJ NYFJV GFZEKJ  CZV ZE FEV GCREV REU JGRTV WZXLIVJ FI JFCZUJ. R GFZEK ZJ R GIZDRIP REU JKRIKZEX TFETVGK ZE XVFDVKIP. CZEV JVXDVEKJ, IRPJ, KIZREXCVJ REU TZITCVJ RIV UVWZEZKV JVK FW GFZEKJ. R JZDGCV TCFJVU TLIMV NZKY CZEV JVXDVEKJ RJ ZKJ SFLEURIZVJ ZJ R  GFCPXFE. KYV CZEV JVXDVEKJ RIV UVCVJ FW KYV GFCPXFE REU KYV VEU GFZEKJ FW KYV JVXDVEKJ RIV MVIKZTVJ FW KYV GFCPXFE. R GFCPXFE NZKY WFLI JZUVJ ZJ R HLRUIZ CRKVIRC. NV TRE ERDV JFDV ZDGFIKREK HLRUIZCRKVIRCJ. IVDVDSVI, KYRK ZE VRTY TRJV NV ERDV R JGVTZWZT JVK FW GFZEKJ. R KIRGVQFZU ZJ R HLRUIZCRKVIRC NZKY FEV GRZI FW GRIRCCVC JZUVJ. R IVTKREXCV ZJ R GRIRCCVCFXIRD NZKY WFLI IZXYK REXCVJ R  JHLRIV ZJ R IVTKREXCV NZKY RCC JZUVJ FW KYV JRDV CVEXKY. KYV IVXLCRI GFCPYVUIR RIV R GRIK FW XVFDVKIZT JKLUP TYZVWCP ZE REKZHLZKP. KYVP YRMV R JPDDVKIZTRC  SVRLKP KYRK WRJTZERKVJ DVE FW RCC RXVJ. KYV WZIJK HLVJKZFE ZE TFEEVTKZFE NZKY  IVXLCRI GFCPYVUIR ZJ: YFN DREP UZWWVIVEK KPGVJ RIV KYVIV? KYREBJ KF KYV  RETZVEK XIVVBJ NV BEFN KYRK KYVIV RIV VORTKCP WZMV KPGVJ FW GFCPYVUIR. RCC FSAVTKJ ZE KYVZI MZVN RIV TFDGFJVU FW WFLI SRJZT VCVDVEKJ: VRIKY, RZI, WZIV REU  NRKVI. KYVP SVCZVMV KYRK KYV WLEURDVEKRC GRIKZTCVJ FW WZIV YRMV KYV JYRGV FW  KVKIRYVUIFE, KYV RZI GRIKZTCVJ YRMV KYV JYRGV FW FTKRYVUIFE, FW NRKVI - KYV  ZTFJRYVUIFE, REU KYV VRIKY - KYV TLSV. KYV WZWKY JYRGV, KYV UFUVTRYVUIFE,  KYVP IVJVIMV WFI KYV JYRGV FW KYV LEZMVIJV ZKJVCW. GCREV XVFDVKIP ZJ KYV JTZVETV FW KYV WLEURDVEKRC GIFGVIKZVJ FW KYV JZQVJ REU JYRGVJ FW FSAVTKJ REU KIVRKJ  XVFDVKIZT GIFGVIKZVJ FW WZXLIVJ. KYV WZIJK HLVJKZFE ZJ, LEUVI NYRK TFEUZKZFEJ  KNF FSAVTKJ RIV VHLRC FI TFEXILVEK ZE JZQV REU JYRGV. EVOK, ZW WZXLIVJ RIV EFK  VHLRC, NYRK JZXEZWZTREK IVCRKZFEJYZG DRP KYVP GFJJVJJ KF VRTY FKYVI REU NYRK  XVFDVKIZT GIFGVIKZVJ TRE KYVP YRMV ZE TFDDFE? KYV SRJZT IVCRKZFEJYZG ZJ  JYRGV. WZXLIVJ FW LEVHLRC JZQV SLK FW KYV JRDV JYRGV, KYRK ZJ, JZDZCRI WZXLIVJ  YRMV DREP XVFDVKIZT GIFGVIKZVJ ZE TFDDFE. ZW WZXLIVJ YRMV EVZKYVI JYRGV  EFI JZQV ZE TFDDFE, KYVP DRP YRMV KYV JRDV RIVR, FI, ZE XVFDVKIZT KVIDJ,  KYVP DRP SV VHLZMRCVEK, FI DRP YRMV VEUCVJJ FKYVI GFJJZSCV IVCRKZFEJYZGJ.  XVFDVKIP ZJ KYV JTZVETV FW KYV GIFGVIKZVJ, DVRJLIVDVEK REU TFEJKILTKZFE FW  CZEVJ, GCREVJ, JLIWRTVJ REU UZWWVIVEK XVFDVKIZT WZXLIVJ.""",
        3: """RM GSV WRHXFHHRLMH LU XLNKFGVIH, GSV DLIW RMULINZGRLM SZH Z IZGSVI HKVXRZO WVURMRGRLM. RMULINZGRLM (WZGZ) RH Z HVG LU NZIPH GSZG SZEV NVZMRMT. RM Z OZITV ZFGLNZGRX VOVXGILMRX XLNKFGVI, RMULINZGRLM NZB YV IVXLIWVW ZMW NZMRKFOZGVW ZH HVJFVMXV LU NRMFGV VOVXGIRXZO KFODSRXS ZIV ZYLFG Z NROORLMGS LU Z HVXLMW ZKZIG; ZMW GSV KIVHVMXV LI ZYHVMXV LU Z KFOHV RM Z KLHRGRLM DSVIV VRGSVI NZB LXXFI RH GSV YZHRX XLWV DSRXS IVKIVHVMGH RMULINZGRLM. RMULINZGRXH RH Z XLOOVXGRLM LU XLNKFGVI GSVLIRVH ZMW MLEVO RMULINZGRLM GVXSMLOLTRVH.RG RH WRUURXFOG GL HZB DSZG GSV UFGFIV SLOWH RM HGLIV ULI RMULINZGRXH. VEVIB WZB DV OVZIM NLIV ZMW NLIV ZYLFG GSV KVMVGIZGRLM LU RMULINZGRXH RMGL GSV NLHG DRWVOB WRUUVIRMT HKSVIVH LU SFNZM ZXGRERGB. GSV OZFMXSRMT LU HKFGMRPH ZMW GSV WVOREVIB LU LFI HKZXV ILXPVGH GL GSVRI LIYRGH DRGS HFXS SRTS ZXXFIZXB XLFOW SZEV YVVM SZIWOB KLHHRYOV DRGSLFG XLNKFGVIH. GSRH, SLDVEVI, WLVH MLG NVZM, GSZG GSV NZXSRMV XZM VEVI YVXLNV "XOVEVIVI" GSZM RGH XIVZGLI. GSV KLRMG RH GSZG GSV NZXSRMV WLVH MLG IVKOZXV NZM, RG LMOB RMXIVZHVH SRH DLIP LFGKFG ZMW NFOGRKORVH SRH KLDVI LEVI GSV ULIXVH LU MZGFIV. RG HSLFOW YV ZODZBH IVNVNYVIVW GSZG GSV NZXSRMV HVIEVH NZM, ZMW MLG GSV LGSVI DZB ILFMW. DRGSLFG NZM, VEVM GSV NLHG KVIUVXG NZXSRMV DLFOW YV LMOB Z FHVOVHH SVZK LU NVGZONZM'H GVXSMRXZO KILTIVHH RH IVUOVXGVW RM GSV GLLOH SV SZH RMEVMGVW. UILN VZIOB GRNVH SV SZH YVVM XVZHVOVHHOB XIVZGRMT ZMW RNKILERMT WVERXVH GL ZHHRHG SRH YIZRM RM XLNKOVGRMT GZHPH WRUURXFOG LI LGSVIDRHV RNKLHHRYOV. GSILFTSLFG GSV XVMGFIRVH NZM SZH WVEVOLKVW ZMW IVURMVW GSV ZYRORGB GL IVXLIW, KILXVHH, ZMW XLNNFMRXZGV RMULINZGRLM. DRGS GSV ZWEVMG LU ZFGLNZGRX WRTRGZO XLNKFGVIH, NZM SZH XIVZGVW WVERXVH GSZG XZM HLOEV XLNKOVGV KILYOVNH DRGSLFG GSV MVVW ULI SFNZM RMGVIEVMGRLM WFIRMT GSV XLFIHV LU HLOFGRLM. ZOGSLFTS LKVIZGRLMH KVIULINVW YB XLNKFGVIH ZIV GSV EVIB YZHRX LMVH (ZWWRGRLM, HFYGIZXGRLM, NFOGRKORXZGRLM ZMW WRERHRLM), TIVZG HKVVW LU LKVIZGRLM RH NLIV GSZM XLNKVMHZGRLM. GSV KIRMXRKZO FHV LU XLNKFGVIH SZH YVVM RM GSV ZIVZ LU ZKKORVW NZGSVNZGRXH. GSV ZKKORXZGRLM LU XLNKFGVIH GL HXRVMGRURX KILYOVNH SZH YVXLNV OZGVI GSZM GSV LIRTRMZO YFHRMVHH, ZKKORXZGRLMH. MLDZWZBH XLNKFGVIH SZEV YVXLNV RMXIVZHRMTOB RNKLIGZMG ZH YZHRX GLLOH ULI ZMZOBHRH. GSRH LKVIZGRLM IVJFRIVH SRTSOB IVURMVW ZMW UOVCRYOVGSV XLMGIRYFGRLMH LU GSV HXRVMGRHGH GL GSV KILTIVHH LU RMULINZGRXH XLMHRHGH LU GSV VEZOFZGRLM, NVZHFIVNVMG ZMW WVHXIRKGRLM LU GSV XZKZYRORGRVH ZMW LU HGIFXGZMW UFMXGRLMZO ZGGIRYFGVH LU ORERMT LITZMRHNH. HFXS HGFWRVH RMELOEV GSV NVGSLWH LU XLNNFMRXZGRLM, UVVWYZXP ZMW XLMGILO RM GSV ORERMT VMGRGB. SVMXV, ZM RNKLIGZMG ZHKVXG LU GSV DLIP RM RMULINZGRXH ULI NZGSVNZGRXRZMH WVZOH DRGS GSV NZGS GSVLIB LU XLNNFMRXZGRLM.RM GVINH LU XLNKFGVI WVEVOLKNVMG RMULINZGRXH RH XLMXVIMVW DRGS GSV WVHRTM ZMW XLMHGIFXGRLM LU VOVXGIRXZO LI VOVXGILMRX ZMZOLTH XZKZYOV LU KVIULINRMT KILXVHHVH XZIIRVW LFG DRGSRM Z ORERMT VMGRGB, RMXOFWRMT GSV HVOVXGRLMZMW VEZOFZGRLM, ZH DVOO ZH GSV HGLIZTV LU RMULINZGRLM. RM GVINH LU FMWVIHGZMWRMTGSV LKVIZGRLM LU GSV SFNZM MVIELFH HBHGVN, RMULINZGRXH XLMGIRYFGVH MVD RMHRTSG RMGL Z DRWV IZMTV LU KILXVHHVH HFXS ZH OVZIMRMT, IVTFOZGRLM ZMW GSV VNLGRLMZO YVSZERLI LU RMWRERWFZO SFNZM YVRMTH ZH DVOO ZH HLXRVGRVH. HKVXRURXZOOB, GSV KILYOVNH LU WVXRHRLM-NZPRMT, GSRMPRMT ZMW HBMGSVHRH, RNZTRMZGRLM ZMW XIVZGREV VMWVZELI LU KVLKOV, XLNV FMWVI GSV HXIFGRMB LU RMULINZGRG RH ZMGRXRKZGVW GSZG GSV UFGFIV WVEVOLKNVMGH LU ZFGLNZGVW RMWFHGIRVH ZMW HLXRVGZO UFMXGRLMH DROO YV YZHVW LM GSV GSVLIVNH WVEVOLKVW UILN RMULINZGRXH, DSRXS GSFH UZI SZH NZWV HRTMRURXZMG XLMGIRYFGRLM GL GSV GVXSMLOLTB LU TFRWVW NRHHROVH, YFHRMVHH ZMW HXRVMGRURX XLNKFGVI ZKKORXZGRLMH, XLNNFMRXZGRLMH ZMW ZFGLNZGRX XLMGILO. RMULINZGRXH RH Z BLFMT HXRVMXV ZMW BVG RG RH RMXIVZHRMTOB ZKKORVW RM EZIRLFH YIZMXSVH LU RMWFHGIB ZMW IVHVZIXS, RMEZWRMT Z DRIZMTV LU URVOWH RM SFNZM ZXGRERGB. RMULINZGRXH VMWVZELIH GL URMW GSV ZMHDVI GL GNZQLI JFVHGRLMH: GSV YVHG DZB LU XLMGILOORMT GSRH LI GSZG KILXVHH, ZMW GSV YVHG DZB LU FGRORARMT Z NZXSRMV (RU KLHHRYOV) ULI XLMGILOORMT GSRH KILXVHH.""",
    },
    "RUS": {    
        1: """Щ ЙШЖГ ЗЖЁШЮБЖЁТ ЪЗЛШ, - СБЫЪШ АШЭЦЁЕ БОТЩЮЦЬЁ ЁЬЯТ АВБИЮБЫБ Т БЁ ЯТЛ ЯШ ЖЬВЪНЬ ЩЬЬЁ ЛБЮБЪБЭ, СБЫЪШ ЭГЖЮЕ, СШС ЧЬЖЖЁВШЖЁЯБЬ ЖБЮЯНЬ БЖЬЯТ, БЖЩЬКШЬЁ ЫВБРЯГУ ЛШБЖ ЯШЖЁБЦКЬЫБ Т РЮБЩЬКЬ СВЗОТЁЖЦ ЯШЪ ЛШБЖБЭ ЪЯЦ, ЧЬЖЖТЮЕЯШЦ АБЪЯЦЁЕЖЦ ЩГИЬ, ЮЬЁЬЁЕ ЩАЬВЬЪ, - Щ ЁЦОЬЮГЬ ЙШЖГ ЗЖЁШЮБЖЁТ ЪЗЛШ Ц ЩГРГЩШФ АВЬЪ ЖБЧБУ ЩЬЮТЙЬЖЁЩЬЯЯГУ БЧВШР ЙЬЮБЩЬСШ.ЙЬЮБЩЬС! ЁБЙЯБ ЖБЮЯНЬ ВБОЪШЬЁЖЦ Щ ЫВЗЪТ ЭБЬУ, Т Щ ЦВСБЭ ЖЩЬЁЬ ЬЫБ ЭЬЪЮЬЯЯБ ИЬЖЁЩЗЬЁ - ЩАЬВЬЪ! Т - ЩГИЬ! - ЁВШЫТЙЬЖСТ АВЬСВШЖЯГУ ЙЬЮБЩЬС!Ц ЩТОЗ ЬЫБ ЫБВЪБЬ ЙЬЮБ Т ЖЭЬЮГЬ, ЫЮЗЧБСТЬ ЫЮШРШ, Ш Щ ЯТЛ - ЮЗЙТ ЧЬЖЖЁВШИЯБУ ЭГЖЮТ, ЁБУ ЩЬЮТЙШЩБУ ЖТЮГ, СБЁБВШЦ Щ ЭБЭЬЯЁГ ЗЁБЭЮЬЯЕЦ - ЁЩБВТЁ ЧБЫБЩ, Щ ХАБЛТ ЧБЪВБЖЁТ - ТЛ ЯТРЩЬВЫШЬЁ.РШЁЬВЦЯЯГУ ЖВЬЪТ АЗЖЁГЯЕ ЩЖЬЮЬЯЯБУ, БЪТЯ ЯШ ЭШЮЬЯЕСБЭ СЗЖСЬ РЬЭЮТ, ЯЬЖЗКЬЭЖЦ Ж ЯЬЗЮБЩТЭБУ ЧГЖЁВБЁБФ СЗЪШ-ЁБ Щ ЫЮЗЧЕ ЧЬРЭЬВЯБЫБ АВБЖЁВШЯЖЁЩШ, ЁЬВРШЬЭГУ ЭЗЙТЁЬЮЕЯГЭ ЩБАВБЖБЭ - "РШЙЬЭ БЯ ЖЗКЬЖЁЩЗЬЁ?" - БЯ ЭЗОЬЖЁЩЬЯЯБ ЪЩТОЬЁЖЦ - ЩАЬВЬЪ! Т - ЩГИЬ! – АБ АЗЁТ С АБЧЬЪШЭ ЯШЪ ЩЖЬЭТ ЁШУЯШЭТ РЬЭЮТ Т ЯЬЧШ.ТЪЬЁ БЯ, БВБИШЦ СВБЩЕФ ЖЬВЪНШ ЖЩБУ ЁВЗЪЯГУ, БЪТЯБСТУ, ЫБВЪГУ АЗЁЕ, Т ЖБРЪШЬЁ ТР ХЁБУ ОЫЗЙЬУ СВБЩТ - АБХРТТ ЯЬЁЮЬЯЯГЬ НЩЬЁГ; ЁБЖСЮТЩГУ СВТС ЪЗИТ ЖЩБЬУ ЭЦЁЬОЯБУ БЯ Щ ЭЗРГСЗ ТЖСЗЖЯБ АВЬЁЩБВЦЬЁ, ТР БАГЁШ - ЯШЗСТ ЖБРЪШЬЁ Т, СШОЪГЭ ИШЫБЭ ЗСВШИШЦ ОТРЯЕ, СШС ЖБЮЯНЬ РЬЭЮФ КЬЪВГЭТ ЮЗЙШЭТ, - БЯ ЪЩТОЬЁЖЦ ЩЖЬ - ЩГИЬ! Т - ЩАЬВЬЪ! РЩЬРЪБФ АЗЁЬЩБЪЯБУ ЪЮЦ РЬЭЮТ...""",
        2: """ЧЁ, ЧШЩНЩШКБУЩШКЦЖШЁФ ШКЫЩО ЫЩЬЬУФЬХЩФ ЯПОПЫКБУУ, ЬЩПОУШПШШЁП ЩЛДПФ ЬЮОЖЛЩФ ШК ЬМЩПФ ТПЧЦП, ЮЭМПЫСОКЙ ЪЫКМК У ЬМЩЛЩОЁ ВПЦЩМПХК, НЫКСОКШЬХУФ ЧУЫ У ЬЩНЦКЬУП, ЬЩАЫКШЙЙ УЬЭЩЫУВПЬХУ ЬЦЩСУМГППЬЙ НЩЬЮОКЫЬЭМПШШЩП ПОУШЬЭМЩ, УЬАЩОЙ УТ ЩЛДПЪЫУТШКШШЁА ЪЫУШБУЪЩМ ЫКМШЩЪЫКМУЙ У ЬКЧЩЩЪЫПОПЦПШУЙ ШКЫЩОЩМ, ВЭЙ ЪКЧЙЭЖ ЪЫПОХЩМ, ЪПЫПОКМГУА ШКЧ ЦИЛЩМЖ У ЮМКСПШУП Х ЩЭПВПЬЭМЮ, МПЫЮ М ОЩЛЫЩ У ЬЪЫКМПОЦУМЩЬЭЖ, МЩТЫЩСОКЙ ЬЮМПЫПШШЮИ НЩЬЮОКЫЬЭМПШШЩЬЭЖ ЫЩЬЬУУ У ЮЭМПЫСОКЙ ШПТЁЛЦПЧЩЬЭЖ ПП ОПЧЩХЫКЭУВПЬХЩФ ЩЬШЩМЁ, ЬЭЫПЧЙЬЖ ЩЛПЬЪПВУЭЖ ЛЦКНЩЪЩЦЮВУП У ЪЫЩБМПЭКШУП ЫЩЬЬУУ, УЬАЩОЙ УТ ЩЭМПЭЬЭМПШШЩЬЭУ ТК ЬМЩИ ЫЩОУШЮ ЪПЫПО ШЁШПГШУЧ У ЛЮОЮДУЧУ ЪЩХЩЦПШУЙЧУ, ЬЩТШКМКЙ ЬПЛЙ ВКЬЭЖИ ЧУЫЩМЩНЩ ЬЩЩЛДПЬЭМК, ЪЫУШУЧКПЧ ХЩШЬЭУЭЮБУИ ЫЩЬЬУФЬХЩФ ЯПОПЫКБУУ.""",
        3: """ЙЛПТЖО ХКИОЩ АТЙЗЕ ЪОЫЮЭ ЦРЫЪЕЭЬРО, ЦБИЯ ЪЪБТЧХМЙ ЧО УСГОМНЛУ ДЦИС, ЙЕАК УЕР Ю ЩЕРН ПЕУБШЕЪЭТ ЖХБУЕЭЬРО, М ИЗЛЮРЖХСЧФ ОВЮХЦЦЕ РХ ТЯЖЪ; УПЩТЛ ЁВЦ СБ ЧРЮПКР, КАР, НФ ВУЧДЮЗЯ, ЯВУЧА ЗКУВ ЪИЙЪЧ, ХЕ БЬКЦЩКЛИ УЭ ПНЩ; ПФЕЩ ЮТУЭЬЪЬ Ш ЬЖ ПДГРСЛ, ЮТУЭЬЖ, ВФЪКПТАЫШЭУЛ Н РПЛРФШ ЁХЧЯРХ. ГЫЖО РБЯТПБЮ, ТИ НЪАС ЯВЁТИ ФЕЖБВТАЫ, Р МКАННЦШ, ФЫБЪК ТИ КИОЦУУЧЁЕЙ; РПРПУ ЁНЪРФЁВО ЧНЧЕЕ Ч СУФПКАЭКЖ, ЕД ДЗБКРВД, ЫОЦ ИЕ СРРТН УЖШР; РЦЦЬХЬБН ФНЩ, ЖЦГУО ФЖТБ ОЕ БЪРЖТ ЖЗЛФЁКЧ УЗЫТ, ЖБРЁ ЧЗЦВЫНФБ ЖЗЫПЁЭД, ПТЯЛА САБ ЛМДХЬ АОЙХЧФМНП Ч УТТЮЗ ТК ТРРКБХ ВБУ ДУХНЦЗУОДЕЦШ З ОБЬРЖ. ЧИМЙ ЯЭУЧДЮРТЛ Р ТЕЗКЩТЭЭЛ ТДАМЖУУ, ВЕ ОЬШТГ РУЙ, ЫОЦ НПЩРФМЗ З ТАВЁУР, ЬЗА ЯЯРНЖМЗТЛ Ч ПНЭЕФ СВОФБ ОЬТ ПАУИИИ Е ХИЪЭЕИД ЙМ ПЮХВРИОД А ВЭО, ШРБС ПАЧПШЗЕЪЬ БУТИЪБ, ХЕАРЭ, ЧИЗЦ ТФПЖ ЦППОИВК, МУЖАЗ В ВРРЙН ЯШУУЧ ХЛИ АЗВЭЭ ДЦИ ЛЫСВЭ, ДЦИ НКОАУНУ М ОЦЛЛЩР ЖТЗЖ ГЮРРХМО: "РДШ!" ЭУЧДЙДСО ЮТУХО, ИЕБУЁШГ Ь ЮААНОН, ЕПЛЬ ЖУУЧИЙ, КОСЭТД Д ОЦЛЯЭЛ; ЁЧАД ПАНО Н ЦЮМРУ О ДХДЯЗМШ Ч ЁХЧДДЯЬЧ, СШХОД ВБУ Д ЦЁКС ЧПА УЬМОЗЮВАБ Е ЦКИОЩ; ЬВФТЗХИ БЫЭЦПКФ КПХЁУИ ИКНЮРЖТАБ ЯАБЭД Н ЗЙМЙ ЭУХРТЮРМКШ ГЙЖ, ОЦГУО ДЙХШ ФИА БЭ ФФЕФЕЗК МЕО ЮУАУУПБИ ОЦГУО, ОУН НГН, ВЙ ГШЗБАЬ ЖУНУЁБТ!""",
    }
}

#############
### SHIFT ###
#############
# def shift_decrypt(ciphertext: str, key: int, alphabet: str):
#     length = len(alphabet)
#     decrypted = []
#     for ch in ciphertext:
#         if ch in alphabet:
#             decrypted.append(alphabet[(alphabet.index(ch) - key + length) % length])
#         else:
#             decrypted.append(ch)
#     return "".join(decrypted)

### ENG
# alphabet = ALPHABETS["ENG"]
# text = TEXTS["ENG"][2]
### RUS
# alphabet = ALPHABETS["RUS"]
# text = TEXTS["RUS"][2]
# for key in range(len(alphabet)):
#     result = shift_decrypt(text, key, alphabet)
#     print(f"{key}: {result[:100]}")
    
    
#####################
### SUBSTITUTIONS ###
#####################
# def get_output(result: Dict[int, str]):
#     for k, v in sorted(result.items(), reverse=True):
#         print(f"{k} {v}")

### ENG
# alphabet: str = ALPHABETS["ENG"]
# text: str = TEXTS["ENG"][3]
### RUS
# alphabet: str = ALPHABETS["RUS"]
# text: str = TEXTS["RUS"][1]

# bigrams, trigrams = {}, {}
# for i1 in alphabet:
#     for i2 in alphabet:
#         for i3 in alphabet:
#             trigram = i1 + i2 + i3
#             count = text.count(trigram)
#             if count > 20:
#                 trigrams[count] = trigram
                
# for i1 in alphabet:
#     for i2 in alphabet:
#         bigram = i1 + i2
#         count = text.count(bigram)
#         if count > 40:
#             bigrams[count] = bigram
                
# get_output(trigrams)
# print()
# get_output(bigrams)

################
### VIGENERE ###
################

### ENG
# alphabet = ALPHABETS["ENG"]
# text = TEXTS["ENG"][1]
# key_length = 5
### RUS
# alphabet = ALPHABETS["RUS"]
# text = TEXTS["RUS"][3]
# key_length = 8

# clean_text = "".join([ch for ch in text if ch in alphabet])
# groups = []
# for each in range(key_length):
#     groups.append(clean_text[each::key_length])

# for group in groups:
#     for ch in alphabet:
#         print(f"{ch}\t{group.count(ch)}")
#     print("\n\n")