version: '3.0'

services:
  frontend:
    container_name: crypto-lab5-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - crypto-lab5
  
  backend:
    container_name: crypto-lab5-backend
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - crypto-lab5

networks:
  crypto-lab5: